### ISSUE TITLE
Multi commands

### ISSUE THREAD

**Issue by YoSiJo** [weareinteractive/ansible-sudo#17]
Please add the following Future:

```
sudo_users:
  - name: 'example'
    commands:
      - '/usr/bin/ls'
      - '/usr/bin/df'
      - '/usr/bin/mailq'
```

This helps greatly with the clarity.
