### ISSUE TITLE
Add support for separate /etc/sudoers files

### ISSUE THREAD

**Issue by bschonec** [weareinteractive/ansible-sudo#29]
Instead of writing to a monolithic file, it's nice to be able to consolidate like-minded sudo tasks into individual /etc/sudoers files.  For example, it's much easier to find sudoers files for oracle stuff if the name of the file is /etc/sudoers.d/oracle.

I think a simple loop in the config.yml task would take care of that.

**Comment by franklinkim** [comment]
hi, I don't really see the point of splitting the files up since you're not supposed to look at them on the servers when you're using a provisioning tool, right!? 

you should only be looking at the ansible configuration files... 

if you really want to have multiple files you could also call the role multiple times with different settings while changing the `sudo_sudoers_file` name.

**Comment by bschonec** [comment]
Calling the role multiple times wouldn't work if you wanted to ensure that the /etc/sudoers.d directory was cleaned of non-Ansible-managed files.

My sudoers file is 800+ lines long and splitting them up into individual files makes sense for me.

**Comment by franklinkim** [comment]
oh wow. ok. 

what about being able to set a `sudoers_file` variable on a user base.
This would allow for backward compatibility.

```yaml
- name: "Creating sudoers configurations"
  template:
    src: "etc/sudoers.d/ansible.j2"
    dest: "{{ sudo_sudoers_d_path }}/{{ item.sudoers_file|default(sudo_sudoers_file) }}"
    validate: "/usr/sbin/visudo -cf %s"
    owner: root
    group: "{{ sudo_sudoers_group }}"
    mode: "0440"
  loop: "{{ sudo_users }}"

- name: "Create sudoers file whitelist"
  set_fact:
    sudoers_whitelist: "{{ sudoers_whitelist | default([]) | union([item.sudoers_file|default(sudo_sudoers_file)]) | unique }}"
  when: purge_other_sudoers_files | bool
  loop: "{{ sudo_users }}"

- name: "List sudoers files"
  find:
    paths: "{{ sudo_sudoers_d_path }}"
    patterns: "*"
  register: sudoers_contents
  when: purge_other_sudoers_files | bool
  changed_when: false

- name: "Remove unmanaged {{ sudo_sudoers_d_path }} files"
  file:
    path: "{{ sudo_sudoers_d_path }}/{{ item.path|basename }}"
    state: absent
  loop: "{{ sudoers_contents.files }}"
  loop_control:
    label: "{{ item.path }}"
  when:
    - purge_other_sudoers_files | bool
    - (item.path|basename) not in sudoers_whitelist
```
